### ISSUE TITLE
Some clarification for a new user

### ISSUE THREAD

**Issue by ctgraham** [jonasraoni/article-importer-plugin#1]
I tripped up on naming convention expectations for the folder structure, and on the error messaging when the DOCTYPE wasn't recognized.

**Comment by jonasraoni** [comment]
Hi @ctgraham!

As you've opened some issues, let me give you an introduction :)

- This plugin was adapted from the [BePress](https://github.com/mfelczak/bepress/) repo, with specific needs in mind (our import files were already following this folder convention and the articles had mixed data formats).

- I didn't read the JATS nor the A++ specification (pure lack of time). I just wrote a XML tool to analyze and extract the existing tags/attributes from the files we had, then setup the import using my good sense. Also, my experience with the PKP code base isn't huge, so maybe there's some "links" missing.

- I've ignored some information, which could be easily added to OJS, since it wasn't needed in our use-case.

- There are some "CUSTOM" comments in the code, which can now be removed.

---

About the folder convention/structure... If the volume/issue/article fields are required by the specification, then we could probably eliminate this... But well, as I've taken the "all-in-one" approach, maybe it's better to leave it this way 🤔
